version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_NAME: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  redis:
    image: redis:alpine

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/server
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
    env_file:
      - .env

  asgiserver:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 9000
    command: daphne clonegram.asgi:application -b 0.0.0.0 -p 9000
    volumes:
      - .:/server
    depends_on:
      - db
    links:
      - db
      - redis
    env_file:
      - .env
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file:
      - .env
    depends_on:
      - server
  
  nginx:
    build: ./proxy
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - 80:80
    depends_on:
      - server
    links:
      - server
      - client

volumes:
  postgres_data:
  static_data:
  media_data: